
interval: 3
destinations:
 - destination: "www.google.com"
   count: 20
 - destination: "www.youtube.com"
   count: 10
 - destination: "www.facebook.com"
   count: 5
 - destination: "www.amazon.com"
   count: 3
 - destination: "www.twitch.tv"
   count: 8
